services:
  postgres:
    image: postgres:17.6-alpine
    container_name: profile-db-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${PG_DB_NAME}
      POSTGRES_USER: ${PG_ADMIN}
      POSTGRES_PASSWORD: ${PG_ADMIN_PASS}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  profiles:
    depends_on:
      postgres:
        condition: service_started
      profiles-test:
        condition: service_completed_successfully
    container_name: profile
    build:
      context: .
      dockerfile: api.Dockerfile
    restart: unless-stopped
    ports:
      - "${PORT}:8000"
    env_file:
      - ./.env

  profiles-test:
    container_name: profiles-test
    build:
      context: .
      dockerfile: test.Dockerfile
    command: pytest /src/tests/ -v -s
    env_file:
      - ./.env


volumes:
  postgres_data: