services:
  postgres:
    image: postgres:17.6-alpine
    container_name: profiles-db-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${PG_DB_NAME}
      POSTGRES_USER: ${PG_ADMIN}
      POSTGRES_PASSWORD: ${PG_ADMIN_PASS}
    ports:
      - "127.0.0.1:${PG_PORT}:5432"
    volumes:
      - profiles_postgres_data:/var/lib/postgresql/data
    networks:
      - istu_services_net

  profiles-test:
    container_name: profiles-test
    build:
      context: .
      dockerfile: test.Dockerfile
    command: pytest /src/tests/ -v -s
    env_file:
      - ./.env
    networks:
      - istu_services_net

  profiles:
    container_name: profiles
    build:
      context: .
      dockerfile: api.Dockerfile
    depends_on:
      postgres:
        condition: service_started
      profiles-test:
        condition: service_completed_successfully
    restart: unless-stopped
    ports:
      - "127.0.0.1:${PORT}:8000"
    env_file:
      - ./.env
    networks:
      - istu_services_net

volumes:
  profiles_postgres_data:

networks:
  istu_services_net:
    external: true