services:
  goods-postgres:
    image: postgres:17.6-alpine
    container_name: goods-db-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${PG_DB_NAME}
      POSTGRES_USER: ${PG_ADMIN}
      POSTGRES_PASSWORD: ${PG_ADMIN_PASS}
    ports:
      - "127.0.0.1:${PG_PORT}:5432"
    volumes:
      - goods_postgres_data:/var/lib/postgresql/data
    networks:
      - istu_services_net

  goods:
    container_name: goods
    build:
      context: .
      dockerfile: api.Dockerfile
    depends_on:
      goods-postgres:
        condition: service_started
    restart: unless-stopped
    ports:
      - "127.0.0.1:${PORT}:8000"
    env_file:
      - ./.env
    networks:
      - istu_services_net

volumes:
  goods_postgres_data:

networks:
  istu_services_net:
    external: true